# Generated by Django 5.2.4 on 2025-07-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('provider', 'Course Provider'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
