# Generated by Django 5.2.4 on 2025-07-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprogress',
            name='last_accessed',
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='watched_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
